dependencies:
  cached_network_image: ^3.3.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  http: ^1.1.0
  intl: ^0.18.1
  lottie: ^2.7.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.25
  uuid: ^3.0.7
description: FMAA Ecosystem Mobile Dashboard
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
environment:
  sdk: '>=3.0.0 <4.0.0'
flutter:
  assets:
  - assets/images/
  - assets/animations/
  - assets/icons/
  uses-material-design: true
name: fmaa_dashboard
version: 1.0.0+1

